logging:
  level:
    root: info

spring:
  profiles:
    active: dev


  servlet:
    multipart:
      max-file-size: 50MB


#  default-produces-media-type: application/json
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


server:
  servlet:
    context-path: /api/v1

