spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-social_db
    username: myuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
        mail:
            smtp:
              trust: '*'
            auth: true
            starttls:
                enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
