services:
  postgres:
    container_name: 'social-book-postgres'
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=book-social_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=myuser
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/data/postgres'
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    restart: unless-stopped

networks:
    spring-demo:
        driver: bridge

volumes:
    postgres:
      driver: local